version: "3"
services:
  books:
    image: okteto.dev/books
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: okteto
      MYSQL_PASSWORD: passw0rd

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: okteto
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: r00t
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    driver_opts:
      size: 1Gi